# Красивые эмодзи для бота
EMOJIS = {
    'success': '✅',
    'error': '❌',
    'warning': '⚠️',
    'training': '🏋️',
    'progress': '📈',
    'stats': '📊',
    'calendar': '📅',
    'timer': '⏱️',
    'friends': '👥',
    'premium': '👑',
    'achievements': '🏅',
    'leaderboard': '🏆',
    'settings': '⚙️',
    'info': 'ℹ️',
    'back': '◀️',
    'menu': '📋',
    'food': '🍎',
    'water': '💧',
    'sleep': '😴',
    'ai': '🤖',
    'fire': '🔥',
    'star': '⭐',
    'heart': '❤️',
    'trophy': '🏆',
    'medal': '🎖️',
}